on:
  push:
  # schedule:
  #   - cron: 0 0 * * * # at the end of each day

jobs:
  get-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: zcash/librustzcash
          path: librustzcash
      - uses: actions/checkout@v2
        with:
          repository: eigerco/uniffi-zcash-lib
          path: uniffi-zcash-lib

      - name: ls
        run: |
          ls -la
          pwd
          bash --version

      - name: Install cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install linux tools
        run: sudo apt-get install -y jq curl

      - name: Get librustzcash libraries used in uniffi-zcash-lib
        run: |
          {
            echo 'USED_LIBS<<EOF'
              cargo metadata --format-version=1 --no-deps --manifest-path=./librustzcash/Cargo.toml | \
              jq -r '.packages[] | .name' | \
              xargs -I {} sh -c "cargo metadata --format-version=1 --no-deps --manifest-path=./uniffi-zcash-lib/lib/Cargo.toml | jq -r '.packages[] | .dependencies[] | .name' | grep '{}' | sort -u"
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Check for diffs of outdated versions of librustzcash dependencies and public API changes
        run: |
          # TODO: Not sure why separating by spaces only itererates over the fisrst element
          USED_LIBS=$(echo $USED_LIBS | tr ' ' ';')
          IFS=';' read -ra arr <<< "$USED_LIBS"
          # IFS=' ' read -r -a env_var_array <<< "$USED_LIBS"

          for crate_name in "${arr[@]}"; do
              echo "CRATE NAME"
              echo $crate_name
              # if [ -z "$crate_name" ]; then
              #     continue
              # fi
              #
              # export CRATE_LATEST_VERSION=$(curl --silent "https://crates.io/api/v1/crates/$crate_name" | jq -r '.crate.max_stable_version')
              # export CRATE_CURRENT_VERSION=$(cargo metadata --format-version=1 -q --manifest-path=./uniffi-zcash-lib/lib/Cargo.toml | jq -r --arg crate_name "$crate_name" '.packages[] | select(.name == $crate_name) | .version')
              #
              # if [ "$CRATE_LATEST_VERSION" = "$CRATE_CURRENT_VERSION" ]; then
              #     echo "$crate_name is up to date. Nothing to do."
              #     continue
              # else
              #     echo "$crate_name is out of date."
              #     echo "latest - $CRATE_LATEST_VERSION"
              #     echo "current - $CRATE_CURRENT_VERSION"
              #     git -C ./librustzcash fetch -q --tags
              #     git -C ./librustzcash checkout -q tags/$crate_name-$CRATE_LATEST_VERSION
              #     rustup -q install nightly --profile minimal
              #     cargo +stable -q install cargo-public-api --locked
              #     cargo public-api --manifest-path=./librustzcash/Cargo.toml -p "$crate_name" -sss diff "$CRATE_CURRENT_VERSION"
              # fi
          done

          # TO READ ON MAC (DELETE LATER)
          # IFS=$'\n' read -r -d '' -a env_var_list <<< "$USED_LIBS"

          # for crate_name in "${env_var_list[@]}"; do
            # echo $crate_name
          # done
