on:
  push:
  # schedule:
  #   - cron: 0 0 * * * # at the end of each day

jobs:
  get-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: zcash/librustzcash
          path: librustzcash
      - uses: actions/checkout@v2
        with:
          repository: eigerco/uniffi-zcash-lib
          path: uniffi-zcash-lib

      - name: Install cargo
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly # public-api needs nightly installed so public-api can use rustdoc JSON output

      - name: Install linux tools
        run: sudo apt-get install -y jq curl

        # Generates env var for next step
        # USED_LIBS - list of librustzcash library names, separated by ';', which are used in the uniffi projects (ex - 'zcash_primitives;zcash_address;')
      - name: Get librustzcash libraries used in uniffi-zcash-lib
        run: |
          {
            echo 'USED_LIBS<<EOF'
              # get the names of all librustzcash packages
              cargo metadata --format-version=1 --no-deps --manifest-path=./librustzcash/Cargo.toml | \
              jq -r '.packages[] | .name' | \
              # intersect their names with the dependencies from uniffi-zcash-lib,
              # in order to get the librustzcash libraries used as dependencies in uniffi-zcash-lib
              # also sort and remove duplicates
              xargs -I {} sh -c "cargo metadata --format-version=1 --no-deps --manifest-path=./uniffi-zcash-lib/lib/Cargo.toml | jq -r '.packages[] | .dependencies[] | .name' | grep '{}' | sort -u"
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Save libs diff checksum as artifact
        uses: actions/download-artifact@v2
        with:
          name: libs_diff_checksum
        continue-on-error: true

        # Generates env var for next step
        # LIBS_WITH_DIFF - list of library names, separated by ';', which are outdated (ex - 'zcash_primitives;zcash_address;')
      - name: Check for for outdated librustzcash lib versions
        env:
          CARGO_TERM_COLOR: always
        run: |
          USED_LIBS=$(echo $USED_LIBS | tr ' ' ';')
          IFS=';' read -ra arr <<< "$USED_LIBS"

          cd ./uniffi-zcash-lib/lib
          # Construct the initial part of the command
          cmd_args=("cargo" "outdated" "--format" "json")

          # Loop through each library(out of $USED_LIBS) and add it as a -p argument value
          for lib_name in "${arr[@]}"; do
            cmd_args+=("-p" "$lib_name")
          done

          # Put the JSON output of cargo outdated in a file
          "${cmd_args[@]}" > output.json

          # Save artifact with data: crate-current_ver-latest_ver
          # In order to use it as a checksum and not create an issue every day if the diff is the same
          jq -r 'select(.crate_name | startswith("uniffi-")).dependencies[] | select(.project != .latest) | (.name+""+.project+""+.latest)' output.json | sort -u > libs_diff_checksum

          # compare if the artifact exits
          if [ -f libs_diff_checksum_artifact ]; then
            cmp -s libs_diff_checksum libs_diff_checksum_artifact
            if [ $? -eq 0 ]; then
                echo "QUIT WORKFLOW"
            fi
          fi


          # From each crate which begins with 'uniffi-' (assuming these are the projects we use librustzcash in)
          # Get the library names, which have different current and latest versions (for ex. 'zcash_primitives zcash_address')
          # Also sort and remove duplicates
          LIBS_WITH_DIFF=$(jq -r 'select(.crate_name | startswith("uniffi-")).dependencies[] | select(.project != .latest) | .name' output.json | sort -u)
          LIBS_WITH_DIFF=$(echo $LIBS_WITH_DIFF | tr ' ' ';')

          echo "LIBS_WITH_DIFF=$LIBS_WITH_DIFF" >> $GITHUB_ENV

      - name: Save libs diff checksum as artifact
        uses: actions/upload-artifact@v2
        with:
          name: libs_diff_checksum_artifact
          path: libs_diff_checksum

      # - name: Diff public API changes between outdated libs
      #   env:
      #     CARGO_TERM_COLOR: always
      #   run: |
      #     IFS=';' read -ra arr <<< "$LIBS_WITH_DIFF"
      #
      #     # use the cargo-public-api tool to diff the public APIs of different versions
      #     cargo +stable -q install cargo-public-api --locked
      #
      #     for lib_name in "${arr[@]}"; do
      #       if [ -z "$lib_name" ]; then
      #         continue
      #       fi
      #
      #       # this way it's faster in a loop, since cargo output takes some time
      #       # to be discussed
      #       LIB_LATEST_VERSION=$(curl --silent "https://crates.io/api/v1/crates/$lib_name" | jq -r '.crate.max_stable_version')
      #       LIB_CURRENT_VERSION=$(cargo metadata --format-version=1 -q --manifest-path=./uniffi-zcash-lib/lib/Cargo.toml | jq -r --arg lib_name "$lib_name" '.packages[] | select(.name == $lib_name) | .version')
      #
      #       echo "OUT OF DATE"
      #       echo "LIBRARY: $lib_name | CURRENT VERSION: $LIB_CURRENT_VERSION | LATEST VERSION: $LIB_LATEST_VERSION"
      #       git -C ./librustzcash fetch -q --tags
      #       git -C ./librustzcash checkout -q tags/$lib_name-$LIB_LATEST_VERSION
      #
      #       # write the diff to files, which we show in the next step
      #       # the reason is to more easily link the exact diffing section to the issue
      #       cargo public-api --color=always --manifest-path=./librustzcash/Cargo.toml -p "$lib_name" -sss diff "$LIB_CURRENT_VERSION" > "${lib_name}.diff"
      #     done
      #
      # # A separate step to show the output, so we can link to it in the issue,
      # # without the extra noise of other commands.
      # # If you change the name of this step, make sure it's changed in the "Create workflow summary" gh command too
      # - name: Show public API diffs
      #   run: |
      #     IFS=';' read -ra arr <<< "$LIBS_WITH_DIFF"
      #
      #     for lib_name in "${arr[@]}"; do
      #       if [ -z "$lib_name" ]; then
      #         continue
      #       fi
      #       echo "\n ${lib_name} \n"
      #       cat "${lib_name}.diff"
      #     done

      # TODO: Discuss if a summary is needed
      # TODO: Write better formatted markdown and add data
      - name: Create workflow summary
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          IFS=';' read -ra arr <<< "$LIBS_WITH_DIFF"

          echo "# New versions of librustzcash libraries" >> $GITHUB_STEP_SUMMARY

          for lib_name in "${arr[@]}"; do
            if [ -z "$lib_name" ]; then
              continue
            fi

            LIB_LATEST_VERSION=$(curl --silent "https://crates.io/api/v1/crates/$lib_name" | jq -r '.crate.max_stable_version')
            LIB_CURRENT_VERSION=$(cargo metadata --format-version=1 -q --manifest-path=./uniffi-zcash-lib/lib/Cargo.toml | jq -r --arg lib_name "$lib_name" '.packages[] | select(.name == $lib_name) | .version')

            echo "CURRENT - \`${lib_name}\` -> ${LIB_CURRENT_VERSION}" >> $GITHUB_STEP_SUMMARY
            echo "LATEST  - \`${lib_name}\` -> ${LIB_LATEST_VERSION}" >> $GITHUB_STEP_SUMMARY
            echo ""
          done

          workflow_url=$(gh run --repo ${{ github.repository }} view ${{ github.run_id }} --json jobs --jq '.jobs[] | select(.name == "${{ github.job }}") | .url, (.steps[] | select(.name == "Show public API diffs") | "#step:\(.number):1")' | tr -d "\n")
          echo "[VIEW DIFF]($workflow_url)" >> $GITHUB_STEP_SUMMARY

      - name: Create issue
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Construct checksum form libs<>versions - maybe write them to file and checksum the file
          # Check if checksum exists for these libs<>versions in Check for for outdated librustzcash lib versions
          # Export checksum as env var from Check for for outdated librustzcash lib versions
          #
          # In this workflow:
          # get env var which contains checksum
          # if exists - do nothing
          # if not exists - create issue and save checksum to state
          # issue can just point to summary or contain the same data. To construct data - add in env var and pass to gh
          # add appropriate label and tag user
