name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: Setting up Ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.0"

      - run: gem install ffi --no-document

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            lib/target
          key: 1-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: 🔨 Build
        run: cargo build --verbose

      - name: 🔎 Test
        run: |
          cargo test --verbose

  build-packages:
    # Kotlin variables/secrets only need to be present in the build stage,
    # as they are checked by gradle.
    # They are required because we use System.getenv()
    # in the build.gradle.kts template for security reasons.
    uses: ./.github/workflows/packages.yml
    with:
      version: "0.0.0" # dummy version we are only testing the build.
      languages: "python,ruby,kotlin,swift"
      kotlin-registry-url: "" # dummy, we are testing the build.
    secrets:
      git-ci-user: ${{ secrets.GIT_CI_USER }}
      git-ci-email: ${{ secrets.GIT_CI_EMAIL }}
      kotlin-registry-username: "" # dummy, we are testing the build.
      kotlin-registry-password: "" # dummy, we are testing the build.
      # Swift needs to clone the package repo for build.
      swift-git-repo-url: ${{ secrets.SWIFT_GIT_REPO_URL }}
